### ISSUE TITLE
how to get the file "model-0-cams.txt"

### ISSUE THREAD

**Issue by xueyingliu** [bastienjacquet/PlaneSweepLib#11]
Thank you for you excellent work! You get R and T matrix from **model-0-cams.txt**,  but what does the **R** and **T** mean? I guess 
**R** = cameraToSystem_R x SystemToWorld_R, and 
**T** = cameraToSystem_T + SystemToWorld_T, 
but  I get error when running the code, wish someone can give me some advice.

**Comment by bastienjacquet** [comment]
Hi,
R and T are the rotation and translation in the Structure-from-Motion convention:
x [image 2D coord] = K [camera internal intrinsic parameters] x ( R x X [world coord in 3D] + T)
You cannot just add translation and multiply rotations, but you can multiply the 4x4 A matrices enclosing the two :
[R | T]
[0 | 1 ]

**Comment by xueyingliu** [comment]
@bastienjacquet ok, thank you for your reply~
